In [108]:
from IPython.display import display, Math, Latex

import pandas as pd
import numpy as np
import numpy_financial as npf
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime

## Group Assignment
### Team Number: XX
### Team Member Names:
### Team Strategy Chosen: RISKY OR SAFE)

In [109]:
tickers_df = pd.read_csv("Tickers_Example.csv", header=None).rename(columns={0:'Ticker'})
tickers_df

     Ticker
0      AAPL
1      ABBV
2       ABT
3       ACN
4       AGN
5       AIG
6      AMZN
7       AXP
8        BA
9       BAC
10     BIIB
11       BK
12      BLK
13      BMY
14        C
15      CAT
16     CELG
17       CL
18       KO
19      LLY
20      LMT
21       MO
22      MON
23      MRK
24      PEP
25      PFE
26       PG
27       PM
28     PYPL
29     QCOM
30     QCOM
31      RTN
32    RY.TO
33  SHOP.TO
34     T.TO
35    TD.TO
36      TXN
37      UNH
38      UNP
39      UPS
40      USB
41      USB

In [110]:
# Create an info cell for each ticker, saving time when filtering the tickers by volume and country.
info_column = {}
hist_column = {}
ticker_obj_lst = []

start_date = "2023-01-01"
end_date = "2023-10-31"

# Add info to dict
for idx, row in tickers_df.iterrows():
    ticker = row[0] # Get ticker name
    ticker = yf.Ticker(ticker)
    info_column[idx] = ticker.fast_info
    hist_column[idx] = ticker.history(start=start_date, end=end_date)
    print('.', end='') # So we can tell if the code is running

# Create column for the info]
tickers_df['Info'] = pd.Series(info_column)
tickers_df['History'] = pd.Series(hist_column)
tickers_df

....

AGN: No timezone found, symbol may be delisted

...........

CELG: No timezone found, symbol may be delisted

......

MON: No timezone found, symbol may be delisted

.........

RTN: No timezone found, symbol may be delisted

............

,Ticker,Info,History
0,AAPL,"lazy-loading dict with keys = ['currency', 'da...",Open H...
1,ABBV,"lazy-loading dict with keys = ['currency', 'da...",Open H...
2,ABT,"lazy-loading dict with keys = ['currency', 'da...",Open H...
3,ACN,"lazy-loading dict with keys = ['currency', 'da...",Open H...
4,AGN,"lazy-loading dict with keys = ['currency', 'da...","Empty DataFrame Columns: [Open, High, Low, Clo..."
5,AIG,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
6,AMZN,"lazy-loading dict with keys = ['currency', 'da...",Open H...
7,AXP,"lazy-loading dict with keys = ['currency', 'da...",Open H...
8,BA,"lazy-loading dict with keys = ['currency', 'da...",Open H...
9,BAC,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
10,BIIB,"lazy-loading dict with keys = ['currency', 'da...",Open H...
11,BK,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
12,BLK,"lazy-loading dict with keys = ['currency', 'da...",Open H...
13,BMY,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
14,C,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
15,CAT,"lazy-loading dict with keys = ['currency', 'da...",Open H...
16,CELG,"lazy-loading dict with keys = ['currency', 'da...","Empty DataFrame Columns: [Open, High, Low, Clo..."
17,CL,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
18,KO,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
19,LLY,"lazy-loading dict with keys = ['currency', 'da...",Open H...
20,LMT,"lazy-loading dict with keys = ['currency', 'da...",Open H...
21,MO,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
22,MON,"lazy-loading dict with keys = ['currency', 'da...","Empty DataFrame Columns: [Open, High, Low, Clo..."
23,MRK,"lazy-loading dict with keys = ['currency', 'da...",Open H...
24,PEP,"lazy-loading dict with keys = ['currency', 'da...",Open H...
25,PFE,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
26,PG,"lazy-loading dict with keys = ['currency', 'da...",Open H...
27,PM,"lazy-loading dict with keys = ['currency', 'da...",Open Hi...
28,PYPL,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
29,QCOM,"lazy-loading dict with keys = ['currency', 'da...",Open H...
30,QCOM,"lazy-loading dict with keys = ['currency', 'da...",Open H...
31,RTN,"lazy-loading dict with keys = ['currency', 'da...","Empty DataFrame Columns: [Open, High, Low, Clo..."
32,RY.TO,"lazy-loading dict with keys = ['currency', 'da...",Open H...
33,SHOP.TO,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
34,T.TO,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
35,TD.TO,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
36,TXN,"lazy-loading dict with keys = ['currency', 'da...",Open H...
37,UNH,"lazy-loading dict with keys = ['currency', 'da...",Open H...
38,UNP,"lazy-loading dict with keys = ['currency', 'da...",Open H...
39,UPS,"lazy-loading dict with keys = ['currency', 'da...",Open H...
40,USB,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...
41,USB,"lazy-loading dict with keys = ['currency', 'da...",Open Hig...

In [111]:
tickers_df.loc[tickers_df['Ticker'] == 'UNH', 'History'].values[0]

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-01-03 00:00:00-05:00,519.106217,519.600482,506.284965,512.690674,3525600,0.0,0.0
2023-01-04 00:00:00-05:00,512.690674,512.690674,494.857603,498.712860,5070400,0.0,0.0
2023-01-05 00:00:00-05:00,495.262893,496.330491,482.896386,484.339630,5497100,0.0,0.0
2023-01-06 00:00:00-05:00,485.950938,487.216254,481.947408,484.379181,4841300,0.0,0.0
2023-01-09 00:00:00-05:00,486.761526,494.254561,482.935923,484.438477,3702800,0.0,0.0
...,...,...,...,...,...,...,...
2023-10-24 00:00:00-04:00,522.859985,530.669983,522.070007,525.000000,1978200,0.0,0.0
2023-10-25 00:00:00-04:00,527.270020,532.359985,520.080017,530.210022,2380100,0.0,0.0
2023-10-26 00:00:00-04:00,525.700012,530.469971,522.520020,528.359985,2675800,0.0,0.0
2023-10-27 00:00:00-04:00,525.989990,527.739990,521.260010,524.659973,2585600,0.0,0.0
2023-10-30 00:00:00-04:00,525.000000,531.820007,522.940002,529.989990,2555400,0.0,0.0

In [115]:
tickers = []
tickers_hist = {}
tickers_long_hist = {}
minVolume = 150000
allowed_currencies = ["USD", "CAD"]
long_start_date = "2018-10-31"
threshold_day = 18
days_in_month = []
counter = 0

CAD_stocks = []
USD_stocks = []

for ticker in tickers_df['Ticker']:

    if tickers_df.iloc[counter]['History'].empty:
        print(ticker, "is delisted.")
    elif ticker in tickers:
        print(ticker, "is a duplicate.")
    else:
        tickers_hist[ticker] = currHist
        tickers_long_hist[ticker] = currTicker.history(start=long_start_date, end=end_date)

        group_months = currHist.reset_index().groupby(pd.Grouper(key='Date', freq='M'))
        dfs = [group for _, group in group_months]
        filtered_dfs = []
        for i, df in enumerate(dfs):
            #recombine all the months with more trading days than set threshold
            if len(df.index) >= threshold_day:
                days_in_month.append(len(df.index))
                filtered_dfs.append(df)
        currHist_updated = pd.concat(filtered_dfs)
        currHist_updated.set_index("Date", inplace=True)

        if tickers_df.iloc[counter]['Info']['currency'] not in allowed_currencies:
            print(ticker, "is not in USD or CAD")
        elif tickers_df.iloc[counter]['History']['Volume'].mean() * (np.mean(days_in_month)) < minVolume:
            print(ticker, "only has a volume of", tickers_df.iloc[counter]['Info']['lastVolume'], "and average days of", np.mean(days_in_month))
        else:
            tickers.append(ticker)
            if tickers_df.iloc[counter]['Info']['currency'] == 'USD':
                USD_stocks.append(ticker)
            elif tickers_df.iloc[counter]['Info']['currency'] == 'CAD':
                CAD_stocks.append(ticker)
                
    counter += 1
                
print("\nValid CAD Stocks:\n",CAD_stocks)
print("\nValid USD Stocks:\n",USD_stocks)

AGN is delisted.
CELG is delisted.
MON is delisted.
QCOM is a duplicate.
RTN is delisted.
USB is a duplicate.

Valid CAD Stocks:
 ['RY.TO', 'SHOP.TO', 'T.TO', 'TD.TO']

Valid USD Stocks:
 ['AAPL', 'ABBV', 'ABT', 'ACN', 'AIG', 'AMZN', 'AXP', 'BA', 'BAC', 'BIIB', 'BK', 'BLK', 'BMY', 'C', 'CAT', 'CL', 'KO', 'LLY', 'LMT', 'MO', 'MRK', 'PEP', 'PFE', 'PG', 'PM', 'PYPL', 'QCOM', 'TXN', 'UNH', 'UNP', 'UPS', 'USB']

In [124]:
def create_df(df):
    """
    This function iterates through the filtered list of stocks and creates a new dict with weekly ticker closing prices
    :param df: filtered stocks DataFrame
    :return: dict containing ticker closing prices resampled to weekly data
    """
    dic = {}
    for i in range(len(df)):
        tick = df[i]
        t_hist = tickers_df.loc[tickers_df['Ticker'] == tick, 'History'].values[0]
        dic[tick] = t_hist.Close
    return dic

CAD_prices = pd.DataFrame(create_df(CAD_stocks))
USD_prices = pd.DataFrame(create_df(USD_stocks))
print(CAD_prices)
print(USD_prices)

                                RY.TO    SHOP.TO       T.TO      TD.TO
Date
2023-01-03 00:00:00-05:00  122.739281  48.790001  25.214359  84.689217
2023-01-04 00:00:00-05:00  123.832161  50.610001  25.520916  85.790459
2023-01-05 00:00:00-05:00  123.467865  48.830002  25.492176  84.384216
2023-01-06 00:00:00-05:00  125.040092  49.560001  25.884954  84.345154
2023-01-09 00:00:00-05:00  125.970009  49.810001  25.827473  84.081490
...                               ...        ...        ...        ...
2023-10-24 00:00:00-04:00  109.029999  71.870003  22.360001  76.830002
2023-10-25 00:00:00-04:00  109.110001  66.900002  22.280001  76.919998
2023-10-26 00:00:00-04:00  110.209999  64.529999  22.320000  77.410004
2023-10-27 00:00:00-04:00  108.470001  64.349998  22.010000  76.160004
2023-10-30 00:00:00-04:00  110.120003  64.860001  22.360001  77.190002

[208 rows x 4 columns]
                                 AAPL        ABBV         ABT         ACN  \
Date
2023-01-03 00:00:00-05:00  124.374802  156.074890  107.430855  266.033325
2023-01-04 00:00:00-05:00  125.657639  157.334015  109.028877  265.127716
2023-01-05 00:00:00-05:00  124.325081  157.141785  108.626930  258.867188
2023-01-06 00:00:00-05:00  128.899490  160.082962  110.126923  264.999725
2023-01-09 00:00:00-05:00  129.426559  155.382843  109.950447  269.468750
...                               ...         ...         ...         ...
2023-10-24 00:00:00-04:00  173.211807  146.309998   94.809998  296.089996
2023-10-25 00:00:00-04:00  170.874893  145.259995   93.570000  292.679993
2023-10-26 00:00:00-04:00  166.670425  145.199997   93.980003  292.040009
2023-10-27 00:00:00-04:00  167.998672  138.929993   92.849998  290.040009
2023-10-30 00:00:00-04:00  170.065933  141.889999   93.000000  292.700012

                                 AIG        AMZN         AXP          BA  \
Date
2023-01-03 00:00:00-05:00  61.738464   85.820000  144.975815  195.389999
2023-01-04 00:00:00-05:00  62.650860   85.139999  148.345963  203.639999
2023-01-05 00:00:00-05:00  62.307484   83.120003  144.796036  204.990005
2023-01-06 00:00:00-05:00  63.327801   86.080002  148.494293  213.000000
2023-01-09 00:00:00-05:00  62.660667   87.360001  148.721741  208.570007
...                              ...         ...         ...         ...
2023-10-24 00:00:00-04:00  59.869999  128.559998  144.419998  182.360001
2023-10-25 00:00:00-04:00  60.959999  121.389999  143.520004  177.729996
2023-10-26 00:00:00-04:00  60.849998  119.570000  143.339996  179.089996
2023-10-27 00:00:00-04:00  59.529999  127.739998  141.309998  179.690002
2023-10-30 00:00:00-04:00  61.000000  132.710007  143.270004  182.350006

                                 BAC        BIIB  ...        PFE          PG  \
Date                                              ...
2023-01-03 00:00:00-05:00  32.757507  272.630005  ...  49.035156  147.817459
2023-01-04 00:00:00-05:00  33.373360  270.809998  ...  47.954201  148.461121
2023-01-05 00:00:00-05:00  33.304932  271.589996  ...  47.504601  146.617889
2023-01-06 00:00:00-05:00  33.637299  279.250000  ...  48.709911  150.109283
2023-01-09 00:00:00-05:00  33.128971  274.720001  ...  46.289719  148.275818
...                              ...         ...  ...        ...         ...
2023-10-24 00:00:00-04:00  25.469999  252.110001  ...  30.025188  149.899994
2023-10-25 00:00:00-04:00  25.549999  246.720001  ...  30.321198  150.600006
2023-10-26 00:00:00-04:00  26.120001  241.080002  ...  30.745478  149.800003
2023-10-27 00:00:00-04:00  25.170000  234.520004  ...  29.709446  147.160004
2023-10-30 00:00:00-04:00  25.690001  237.210007  ...  30.143591  149.259995

                                  PM       PYPL        QCOM         TXN  \
Date
2023-01-03 00:00:00-05:00  97.269943  74.580002  105.070328  158.244385
2023-01-04 00:00:00-05:00  97.202728  77.690002  109.314308  164.023041
2023-01-05 00:00:00-05:00  96.809029  76.269997  107.226631  161.851181
2023-01-06 00:00:00-05:00  99.372810  76.480003  113.048622  169.830811
2023-01-09 00:00:00-05:00  98.230164  77.080002  112.333122  171.304550
...                              ...        ...         ...         ...
2023-10-24 00:00:00-04:00  90.830002  54.240002  109.389999  145.585480
2023-10-25 00:00:00-04:00  90.029999  51.490002  104.779999  140.502075
2023-10-26 00:00:00-04:00  89.709999  51.750000  105.620003  142.701920
2023-10-27 00:00:00-04:00  87.470001  50.389999  106.459999  141.819992
2023-10-30 00:00:00-04:00  89.389999  51.049999  107.830002  140.500000

                                  UNH         UNP         UPS        USB
Date
2023-01-03 00:00:00-05:00  512.690674  203.609451  168.576324  42.753723
2023-01-04 00:00:00-05:00  498.712860  205.237717  170.336365  44.084991
2023-01-05 00:00:00-05:00  484.339630  199.195541  167.191406  43.740200
2023-01-06 00:00:00-05:00  484.379181  207.954712  172.105957  44.353161
2023-01-09 00:00:00-05:00  484.438477  207.415253  174.741196  44.640484
...                               ...         ...         ...        ...
2023-10-24 00:00:00-04:00  525.000000  205.440002  147.591537  31.389999
2023-10-25 00:00:00-04:00  530.210022  205.220001  145.229187  31.290001
2023-10-26 00:00:00-04:00  528.359985  202.240005  136.610153  31.770000
2023-10-27 00:00:00-04:00  524.659973  201.720001  133.269272  30.639999
2023-10-30 00:00:00-04:00  529.989990  205.800003  137.173538  31.309999

[208 rows x 32 columns]

## Contribution Declaration

The following team members made a meaningful contribution to this assignment:

Insert Names Here.